"""empty message

Revision ID: 33225911760
Revises: d31aed1e5f3
Create Date: 2015-01-15 20:49:52.556030

"""

# revision identifiers, used by Alembic.
revision = '33225911760'
down_revision = 'd31aed1e5f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_purchases',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_purchases')
    ### end Alembic commands ###
