"""empty message

Revision ID: 3336999d0cc
Revises: 4322143a8332
Create Date: 2015-02-10 10:33:09.538429

"""

# revision identifiers, used by Alembic.
revision = '3336999d0cc'
down_revision = '4322143a8332'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('company_purchases',
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.Text(), nullable=True),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.alter_column(u'company', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text(u"nextval('company_row_id_seq'::regclass)"))
    op.alter_column(u'company_contact', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column(u'contract', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'contract', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column(u'company_contact', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column(u'company', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text(u"nextval('company_row_id_seq'::regclass)"))
    op.drop_table('company_purchases')
    op.drop_table('roles')
    op.drop_table('users')
    ### end Alembic commands ###
