"""empty message

Revision ID: 3340c7bbbb53
Revises: 563c7ff8a7
Create Date: 2015-03-24 18:18:15.001523

"""

# revision identifiers, used by Alembic.
revision = '3340c7bbbb53'
down_revision = '563c7ff8a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text(u"nextval('company_row_id_seq'::regclass)"))
    op.alter_column('company_contact', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('contract', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('company_contact', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('company', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text(u"nextval('company_row_id_seq'::regclass)"))
    ### end Alembic commands ###
