"""empty message

Revision ID: 4322143a8332
Revises: None
Create Date: 2015-02-10 10:32:58.828185

"""

# revision identifiers, used by Alembic.
revision = '4322143a8332'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('bus_type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('contract',
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('contract_number', sa.String(length=255), nullable=True),
    sa.Column('county', sa.String(length=255), nullable=True),
    sa.Column('type_of_contract', sa.String(length=255), nullable=True),
    sa.Column('pa', sa.String(length=255), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('spec_number', sa.String(length=255), nullable=True),
    sa.Column('controller_number', sa.Integer(), nullable=True),
    sa.Column('commcode', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_table('company_contact',
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('company_contact_id', sa.String(length=32), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('address_1', sa.String(length=255), nullable=True),
    sa.Column('address_2', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('fax_number', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('fin', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('company_contact_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_contact')
    op.drop_table('contract')
    op.drop_table('company')
    ### end Alembic commands ###
