"""empty message

Revision ID: 49f22e168b07
Revises: 3340c7bbbb53
Create Date: 2015-04-13 15:57:42.126227

"""

# revision identifiers, used by Alembic.
revision = '49f22e168b07'
down_revision = '3340c7bbbb53'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_updated',
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('last_updated')
    )
    op.alter_column(u'company', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text(u"nextval('company_row_id_seq'::regclass)"))
    op.alter_column(u'company_contact', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column(u'contract', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'contract', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column(u'company_contact', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column(u'company', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text(u"nextval('company_row_id_seq'::regclass)"))
    op.drop_table('last_updated')
    ### end Alembic commands ###
