"""empty message

Revision ID: 4ad9b9c7cb19
Revises: 3336999d0cc
Create Date: 2015-03-23 14:36:18.931479

"""

# revision identifiers, used by Alembic.
revision = '4ad9b9c7cb19'
down_revision = '3336999d0cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_purchases')
    op.alter_column('company', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('company_contact', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('contract', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('company_contact', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('company', 'row_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('company_purchases',
    sa.Column('row_id', sa.INTEGER(), nullable=False),
    sa.Column('item', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('row_id', name=u'company_purchases_pkey')
    )
    ### end Alembic commands ###
