"""empty message

Revision ID: 563c7ff8a7
Revises: 4ad9b9c7cb19
Create Date: 2015-03-23 17:37:17.817529

"""

# revision identifiers, used by Alembic.
revision = '563c7ff8a7'
down_revision = '4ad9b9c7cb19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_upload_password',
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('password')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_upload_password')
    ### end Alembic commands ###
