"""empty message

Revision ID: d31aed1e5f3
Revises: None
Create Date: 2015-01-14 16:42:20.652566

"""

# revision identifiers, used by Alembic.
revision = 'd31aed1e5f3'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('contracts')
    op.drop_table('company')
    op.drop_table('company_contact')
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=30), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'active')
    op.create_table('company_contact',
    sa.Column('company_contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('address_1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('address_2', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fax_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('company_contact_id', name=u'company_contact_pkey')
    )
    op.create_table('company',
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bus_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('company_id', name=u'company_pkey')
    )
    op.create_table('contracts',
    sa.Column('contracts_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contract_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('county', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type_of_contract', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pa', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('spec_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('contact_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('controller_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('commcode', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('contracts_id', name=u'contracts_pkey')
    )
    op.drop_table('roles')
    ### end Alembic commands ###
